language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio platform install https://github.com/platformio/platform-espressif8266.git#feature/stage
script:
- platformio run
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qgTcRCVBZ8EwzdAX2ywmj01fkUbTebM2iXMpn2GqhF3MFc7M3sPJPbIRM88AdK4Lg9I+GWBWaXr4Zr8UmEkoY1/eI6B1oftl80vBF+5j3Z/SB3dhLb6nMeK+FGHm9DakM0VSZo1Z+GWq1lkPf3DkKmxtJtunnF/UlbOk4OMbfxT5dpJwChUQzNiA4PNKD7xJ1Vou5R0DT9OJIYTp8GRkmSuRmiPwL36+2BVueoJuDVNoEhDOilN14xdt1/8LDZ/SiybKd8EZ14MT0S6/E3XZ0sDylmrYdpsrLRr/OFiucg6cS0e1GRiEYnEF/7gCe2+f0FYc6zpHxWB25kaQrIOsruW1ABUUTalOPekh5AZtXjhziyCbQYaGqp+oQkLuoetB0X3kn4QCy5ecUEbh1oqSAgxIwZ+ArV5O/jCOKAvvwYFWV7xezwktvHgqG0iuYoblp5zYFSFSC+iGeE0l4PAvYjVtoyZZMT4q+ckvQDFKGOjoj553/pTef4uTjhwc6ZQ2K9jDxII5JB4ub9mz6O5LyPgB6XbNyWibJdyg2oGlMlgXFVE39Z4k/SKWC0uJoUyLow8M4PyUEy5XNtcarbhwfslLfNkAjB1qqMnlu8H0oKXt/SGevRoJ46Iug4JceDF1vR/DXCfeKkQJmvc8A9guJhPw6xaLWRtLx202iTADl5k=
  file: ".pioenvs/nodemcuv2/firmware.bin"
  on:
    repo: thingsSDK/thingsSwitch
    tags: true